### ISSUE TITLE
🐛[BUG] 页面白屏

### ISSUE THREAD

**Issue by xieqingtian** [arvinxx/dumi-theme-antd-style#1]
### 🐛 bug 描述

安装后启动项目白屏

### 📷 复现步骤

1. 安装 dumi-theme-antd-style
2. 启动项目

### 🏞 期望结果
正常显示

### © 版本信息

- dumi-theme-antd-style 版本: 0.10.2
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/20181476/220569448-bf498f76-4357-48d6-adbe-64221aad60a8.png)

**Comment by arvinxx** [comment]
Get 晚上修
