### ISSUE TITLE
🧐[问题]如果不需要显示上一篇、下一篇按钮，该如何重写或者设置

### ISSUE THREAD

**Issue by nbbjack** [arvinxx/dumi-theme-antd-style#119]
### 🧐 问题描述
如果不需要显示上一篇、下一篇按钮，该如何重写或者设置

**Comment by nbbjack** [comment]
已解决

**Comment by caofuchang** [comment]
> 已解决

你好，请问怎么解决的？

**Comment by nbbjack** [comment]
> > 已解决
> 
> 你好，请问怎么解决的？

https://github.com/nbbjack/dumi-theme-antd-style/commit/8534c0fa9077172a0b65ef0adc26cf7c8ea417f3
