### ISSUE TITLE
👑 [需求] contentMaxWidth 希望支持 string 类型，如 "100%"

### ISSUE THREAD

**Issue by CJY0208** [arvinxx/dumi-theme-antd-style#12]
### 🥰 需求描述

目前 contentMaxWidth 仅支持数字，部分 demo 场景希望充分利用屏幕宽度

希望 contentMaxWidth 可调整至 100% 相对值

**Comment by arvinxx** [comment]
直接设成100%会有问题吗？除了类型定义出错以外

**Comment by CJY0208** [comment]
用到了 contentMaxWidth 的 max-width 属性会失效，因为 `contentMaxWidth` 变量目前在 cssinjs 中的使用方式为 `max-width: ${contentMaxWidth}px`

会得到 `max-width: 100%px`

能够看到的影响就是，content 区域宽度固定变成了 960px

![image](https://user-images.githubusercontent.com/18415774/225791146-647220fc-e459-4fcc-9386-5910c9fe0653.png)

**Comment by arvinxx** [comment]
👌🏻 了解了，我处理下

**Comment by CJY0208** [comment]
contentMaxWidth 我还有一个疑惑，目前 PC 状态下，contentMaxWidth 生效的条件是媒体查询 `${responsive.desktop}` 也生效，否则只会使用 `max-width: 960px`

这个限制是否可以去掉？contentMaxWidth 默认值 1152 和 960 相差也不大，不太理解为啥要做这个限制
