### ISSUE TITLE
🐛[BUG] dumi 2.3.x && Redux Devtools  已经不能正常运行了 切换路由会白屏 

### ISSUE THREAD

**Issue by eternallycyf** [arvinxx/dumi-theme-antd-style#121]
### 🐛 bug 描述

dumi 2.3.x 已经不能正常运行了 切换路由会白屏 

### 📷 复现步骤

直接用 [dumi-theme-antd-style](https://github.com/arvinxx/dumi-theme-antd-style) 仓库代码 
git clone xxx && pnpm i

2.安装了 chrome Redux Devtools 
- 开启了 切换路由就会白屏
- 没开 控制台也会有报错的

### 🏞 期望结果

切换路由后 不白屏

### 💻 复现代码

就用 dumi-theme-antd-style 代码即可

### © 版本信息

- dumi-theme-antd-style 版本: 最新
- 浏览器环境 chrome 最新
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![录屏2024-05-11 14 30 33](https://github.com/arvinxx/dumi-theme-antd-style/assets/63464198/e269b1b8-6ec6-4ca8-af23-56db1ea48e5c)

使用dumi-antd-style 用 vercel 部署的 会出现白屏 && 开启了chrome Redux Devtools
<img width="1436" alt="截屏2024-05-11 15 08 01" src="https://github.com/arvinxx/dumi-theme-antd-style/assets/63464198/7f0f10b4-933e-4906-9677-7c611aa66fa9">

**Comment by Evey-huang** [comment]
我也遇到了这个问题，请问你解决了吗

**Comment by eternallycyf** [comment]
> 我也遇到了这个问题，请问你解决了吗

先锁定版本把 @Evey-huang 

```json
"devDependencies":{
    "dumi": "~2.2.x",
},
  "resolutions": {
    "dumi": "2.2.17"
  },
```

**Comment by Evey-huang** [comment]
> > 我也遇到了这个问题，请问你解决了吗
> 
> 先锁定版本把 @Evey-huang
> 
> ```json
> "devDependencies":{
>     "dumi": "~2.2.x",
> },
>  "resolutions": {
>     "dumi": "~2.2.x"
> },
> ```

这个方法有用！谢谢你

**Comment by arvinxx** [comment]
已在 #122 修复
