### ISSUE TITLE
🐛[BUG] FrontMatter 中 toc: false 无效

### ISSUE THREAD

**Issue by CJY0208** [arvinxx/dumi-theme-antd-style#13]
### 🐛 bug 描述

`FrontMatter` 中 `toc: false`  无效， `dumi 2x` 仍支持[此功能](https://d.umijs.org/guide/page-config#%E9%94%9A%E7%82%B9%E7%9B%AE%E5%BD%95%E9%85%8D%E7%BD%AE)

查阅代码，`src/pages/Docs/index.tsx` 中 `<Toc />` 无条件加载，希望可受  `toc: false` 控制

### 💻 复现代码

--

### © 版本信息

--

**Comment by arvinxx** [comment]
能举例说明下什么场景下不需要 toc 吗？以及会需要端的差异么？比如 pc 不需要，mobile 需要。或pc需要 mobile 不需要

**Comment by CJY0208** [comment]
> 什么场景下不需要 toc ？

可能存在最大限度腾出空间，给 doc content 进行效果演示的场景，如 Page 页面级组件

这类情景下可能会把 sidebar 都给干掉，也需要配合 contentMaxWidth 最大化 content 内容宽度

> 会需要端的差异么？

不确定，我们这边没有场景
