### ISSUE TITLE
👑 [需求] 希望支持 FrontMatter 修改 siteToken 功能，各页面可自定义样式

### ISSUE THREAD

**Issue by CJY0208** [arvinxx/dumi-theme-antd-style#14]
### 🥰 需求描述

如

```markdown
---
contentMaxWidth: 1152
---

# Demo
```

**Comment by arvinxx** [comment]
应该不会开所有 token，感觉没必要，核心需要的哪个？ contentMaxWidth 么？

**Comment by CJY0208** [comment]
感觉可以把   contentMaxWidth, footerHeight, sidebarWidth, tocWidth 开出来，不同文档可以灵活利用页面容器的面积

如果可以控制 tocWidth，是不是 #13 的问题也能解决？

头部因为是 dumi 主要导航位， DumiSiteProvider 的其他属性似乎是控制整站样式的，确实没必要改动

**Comment by charmer-hash** [comment]
这个侧边栏可以配置三级菜单吗
