### ISSUE TITLE
🐛[BUG] 页面右侧导航点击跳转锚点时，会多向上滚动一截

### ISSUE THREAD

**Issue by Peek-A-Booo** [arvinxx/dumi-theme-antd-style#19]
### 🐛 bug 描述

页面右侧导航点击跳转锚点时，会多向上滚动一截。官方自带的主题不会

### 🏞 期望结果

能够正确的跳转到锚点所在元素位置

### © 版本信息

- dumi-theme-antd-style 版本: [0.19.4]
- 浏览器环境
- 开发环境 [mac OS]

**Comment by maquannene** [comment]
mark

**Comment by arvinxx** [comment]
fixed in #32
