### ISSUE TITLE
🐛[BUG] 首页按照hero.actions 配置的link无法跳转新窗口

### ISSUE THREAD

**Issue by Peek-A-Booo** [arvinxx/dumi-theme-antd-style#21]
### 🐛 bug 描述

我在themeConfig里配置hero.actions的link，即使配置完整的url也只能跳转到项目内页面

### 🏞 期望结果

期望配置完整url link时能够window.open打开新窗口跳转外链

### 💻 复现代码

```
hero: {
  actions: [
    { text: '开始使用', link: '/hooks' },
    { text: 'Github', link: 'https://github.com/xx/xx' },
  ],
},
```

### © 版本信息

- dumi-theme-antd-style 版本: [0.19.4]
- 浏览器环境
- 开发环境 [mac OS]

**Comment by zhaoyutaotao** [comment]
还没有恢复吗，还是无法跳转http地址
