### ISSUE TITLE
🧐[问题]调试、开发

### ISSUE THREAD

**Issue by maquannene** [arvinxx/dumi-theme-antd-style#29]
### 🧐 问题描述

clone 了你的仓库，没办法启动起来，跑 dev 和 start 都不行。

麻烦讲一下这个仓库是怎么开发的？

**Comment by arvinxx** [comment]
正常 pnpm i , npm run start 就能起来了。你遇到什么报错？可以贴出来

**Comment by maquannene** [comment]
运行之后 Node 自动就挂了。
找到问题了，这个仓库没有 lock，安装的 dumi 的版本有问题，换另外一个版本就可以了。

**Comment by arvinxx** [comment]
dumi 版本有问题的话，提一下给 dumi 哈。我们默认不锁版本，自动升级依赖的
