### ISSUE TITLE
👑 [需求] 需要有一个配置项，可以控制StrictMode的启用

### ISSUE THREAD

**Issue by scliuyang** [arvinxx/dumi-theme-antd-style#33]
### 🥰 需求描述
主题默认使用了React StrictMode包括内容
代码在： https://github.com/arvinxx/dumi-theme-antd-style/blob/master/src/layouts/DocLayout/index.tsx#L68
但是我们内部的依赖短时间内无法升级到最新的能力，导致组件行为出现了一些异常，需要关闭StrictMode

### 🧐 解决方案
增加一个控制项，可以手动关闭 StrictMode

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/12167648/232368136-830e34d4-cbf4-4b11-bc4c-4b414b2ae305.png)

**Comment by arvinxx** [comment]
生产环境下 StrictMode 应该会自动关闭的吧？

**Comment by scliuyang** [comment]
但是在开发的时候导致组件行为异常，开发环境强制开启Production模式我感觉好奇怪

**Comment by arvinxx** [comment]
> 但是在开发的时候导致组件行为异常，开发环境强制开启Production模式我感觉好奇怪

我去掉吧先
