### ISSUE TITLE
🧐[问题]如何将文档中的 npm 等信息去掉？

### ISSUE THREAD

**Issue by huyinglin** [arvinxx/dumi-theme-antd-style#41]
### 🧐 问题描述
如何将下图中的内容去掉，或者支持可配置？

### 🚑 截图
![image](https://user-images.githubusercontent.com/30167928/234199895-9c8acf14-9848-44f8-8724-1c94172e5cb4.png)

**Comment by arvinxx** [comment]
参考：https://dumi-theme-antd-style.arvinx.app/config/api-header
