### ISSUE TITLE
👑 [需求]首页 actions 按钮应该支持打开第三方链接

### ISSUE THREAD

**Issue by Cyan-Xmw** [arvinxx/dumi-theme-antd-style#46]
### 🥰 需求描述

![image](https://github.com/arvinxx/dumi-theme-antd-style/assets/40554571/fd796a36-4b41-49e0-ac4b-0d0934ed7566)

**Comment by arvinxx** [comment]
现在可以配置下 `openExternal:true`

不过感觉可以加个判断，如果是http 开头的直接打开新页面好了

**Comment by arvinxx** [comment]
close with #57
