### ISSUE TITLE
🐛[BUG] 通过yarn安装，启动时报错

### ISSUE THREAD

**Issue by NickJiangDev** [arvinxx/dumi-theme-antd-style#51]
### 🐛 bug 描述

通过yarn安装，启动时报错

### 📷 复现步骤

<img width="854" alt="image" src="https://github.com/arvinxx/dumi-theme-antd-style/assets/45092189/11e6a757-913b-4cea-adff-48c14f216d29">

### 🏞 期望结果

正常启动

### 💻 复现代码

<img width="393" alt="image" src="https://github.com/arvinxx/dumi-theme-antd-style/assets/45092189/f71b6458-f2a0-4f10-93fa-b2e5751288c9">

**Comment by arvinxx** [comment]
似乎是antd依赖的问题…需要我给主题包加下antd的依赖。晚点提个pr修下
