### ISSUE TITLE
🧐[问题] 网页底部的footer，前面部分怎么设置的？

### ISSUE THREAD

**Issue by Lands-1203** [arvinxx/dumi-theme-antd-style#56]
![image](https://github.com/arvinxx/dumi-theme-antd-style/assets/61341868/343803c0-5c40-4b98-9ad7-2bdbe7d00829)
![image](https://github.com/arvinxx/dumi-theme-antd-style/assets/61341868/7dbe8dc1-33d2-40ee-9318-79ecc4302f80)

**Comment by arvinxx** [comment]
close with #58
