### ISSUE TITLE
如何关闭Footer？

### ISSUE THREAD

**Issue by owenchen1004** [arvinxx/dumi-theme-antd-style#7]
请问在站点模式中的dumi项目里导入此包，如何关闭Footer呢？

**Comment by arvinxx** [comment]
可以自定义 footer ，因为footer组件里会支持图标等react组件，因此footer column 的配置项没法做在themeConfig。需要引入组件然后自行传 props。

这块文档还没写，可以直接参看 src/slots/Footer 的写法

**Comment by arvinxx** [comment]
文档已补充： https://dumi-theme-antd-style.arvinx.app/
