### ISSUE TITLE
🧐[问题] atomId是否可以切换大小写

### ISSUE THREAD

**Issue by mengxinssfd** [arvinxx/dumi-theme-antd-style#74]
### 🧐 问题描述

组件名是大驼峰命名的，但是目录是小写加中划线命名的，导致目前源码、文档的位置无法匹配，那么atomId是否可以切换大小写呢？

**Comment by arvinxx** [comment]
可以，欢迎提pr

**Comment by mengxinssfd** [comment]
> 可以，欢迎提pr

- `atomId.${'camel' | 'kebab' | 'snake' | 'pascal' }`: 在 markdown 文件中标记的 `atomId` ；
  - kebab：小写加中划线；例如 {atomId.kebab}, atomId 设为 test-atomId，实际转换为 test-atom-id
  - camel：小驼峰；例如 {atomId.camel}, atomId 设为 test-atomId，实际转换为 testAtomId
  - snake：小写加下划线；例如 {atomId.snake}, atomId 设为 test-atomId，实际转换为 test_atom_id
  - pascal：大驼峰；例如 {atomId.pascal}, atomId 设为 test-atomId，实际转换为 TestAtomId

我是这样设计的，你看看行不，行的话我就推了

**Comment by arvinxx** [comment]
可以的，推吧
