### ISSUE TITLE
🧐[问题]是否能将demo示例代码的着色器取消

### ISSUE THREAD

**Issue by Shnnli** [arvinxx/dumi-theme-antd-style#77]
### 🧐 问题描述

能不能设置对demo.md的代码不进行着色，着色后切换主题的那个选项就失效了，而且着色时会有着色准备闪烁的过程，让我看着有点难受，所以我想把这个功能禁用，在文档描述中没找到对应的配置项
### 🚑 其他信息
![image](https://github.com/arvinxx/dumi-theme-antd-style/assets/116421920/30b170a9-ae44-4319-9bcd-2b2ebed59fc0)

![image](https://github.com/arvinxx/dumi-theme-antd-style/assets/116421920/6cd0882f-8284-413d-8c2c-7fd21251f4d0)

**Comment by arvinxx** [comment]
https://dumi-theme-antd-style.arvinx.app/guide/syntax-highlighter

现在是支持两种着色器，没用shiki的时候会用prism兜底，但目前好像暂时没开出来口子可以全局配置prism 或者shiki，这我后面加下~

**Comment by Shnnli** [comment]
> https://dumi-theme-antd-style.arvinx.app/guide/syntax-highlighter
> 
> 现在是支持两种着色器，没用shiki的时候会用prism兜底，但目前好像暂时没开出来口子可以全局配置prism 或者shiki，这我后面加下~

还有一个问题是着色器会让切换主题的那个选项失效

**Comment by Shnnli** [comment]
解决了，我把SourceCode这个组件手动传了type="prism"进去
