### ISSUE TITLE
🧐[问题]安装好库之后，不经过任何改动，直接start项目。跑起来了发现首页的名称错位了

### ISSUE THREAD

**Issue by Peek-A-Booo** [arvinxx/dumi-theme-antd-style#79]
### 🧐 问题描述

安装好库之后，不经过任何改动，直接start项目。跑起来了发现首页的名称错位了。

### 💻 示例代码

没有使用Hero组件和themeConfig.hero配置，直接用的是 index.md 里面的hero信息
```
import { defineConfig } from 'dumi';

export default defineConfig({
  outputPath: 'docs-dist',
  themeConfig: {
    logo: '/favicon.png',
    name: 'LX-UI',
  },
  favicons: ['/favicon.png'],
});
```

index.md配置如下
---
hero:
  title: LX-UI
  description: 一个简简单单的 React UI Library
  actions:
    - text: 开始使用
      link: /guide
    - text: Github
      link: https://github.com/LTopx/L-UI
features:
  - title: Hello
    emoji: 💎
    description: Put hello description here
  - title: World
    emoji: 🌈
    description: Put world description here
  - title: '!'
    emoji: 🚀
    description: Put ! description here
---

### 🚑 其他信息

![img](https://l-resource-1258217390.cos.ap-shanghai.myqcloud.com/image/bug.png)

**Comment by Peek-A-Booo** [comment]
发现是Tailwindcss样式污染了，不知道有没有什么比较好的解决方案

**Comment by arvinxx** [comment]
> 发现是Tailwindcss样式污染了，不知道有没有什么比较好的解决方案

Tailwindcss 的啥样式污染了啥样式？具体描述一下？
