### ISSUE TITLE
🧐[问题] 如何自定义设置主题的一些初始值，如：getCustomToken  定义的一些宽度等

### ISSUE THREAD

**Issue by JaylanChen** [arvinxx/dumi-theme-antd-style#9]
### 🧐 问题描述

1. 如何自定义设置主题的一些初始值，如：getCustomToken  定义的一些宽度，[tocWidth、contentMaxWidth...](https://github.com/arvinxx/dumi-theme-antd-style/blob/master/src/styles/customToken.ts#L41)

2. ApiHeader Npm、UNPKG等，能否自定义
![image](https://user-images.githubusercontent.com/7055008/223463184-45119a85-ba5f-4aa5-9680-06617f65d964.png)

**Comment by arvinxx** [comment]
> 如何自定义设置主题的一些初始值，如：getCustomToken 定义的一些宽度，[tocWidth、contentMaxWidth...](https://github.com/arvinxx/dumi-theme-antd-style/blob/master/src/styles/customToken.ts#L41)

目前暂不支持配置修改，应该可以加。但需要明确一下你需要是通过配置来修改默认值，还是通过运行时来修改，两种模式的修改方式不一样。

> 2. ApiHeader Npm、UNPKG等，能否自定义

目前暂时不行，但可以作为 Feature 加一下。你需要哪些自定义的？可以列下，如果常见的话我可以都内置进去，并通过配置来开启或关闭。不常见的话估计要做个 slots 供外部覆盖了

**Comment by arvinxx** [comment]
> 如何自定义设置主题的一些初始值

详见 `siteToken` 配置项 ： https://dumi-theme-antd-style.arvinx.app/config#sitetoken

> ApiHeader Npm、UNPKG等，能否自定义
详见 ApiHeader 自定义配置：https://dumi-theme-antd-style.arvinx.app/config/api-header
